version: '3.9'

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    #build:
    #  context: ..
    #  dockerfile: ./docker/Dockerfile
    #  args:
    #    RELEASE_VERSION: 9.0.2
    links:
      - db:database
    env_file:
      - ./envs/sepolia-blockscout.env
    environment:
      # Override RPC URLs for Sepolia
      ETHEREUM_JSONRPC_HTTP_URL: http://13.218.235.173:8545/
      ETHEREUM_JSONRPC_TRACE_URL: http://13.218.235.173:8545/
      ETHEREUM_JSONRPC_WS_URL: ws://13.218.235.173:8545/
      CHAIN_ID: '11155111'
      # Start from latest block only
      FIRST_BLOCK: '9423055'
      # LAST_BLOCK: '9423055'
    ports:
      - "4000:4000"  # Expose backend API directly

  #nft_media_handler:
  #  depends_on:
  #    - backend
  #  extends:
  #    file: ./services/nft_media_handler.yml
  #    service: nft_media_handler
  #  build:
  #    context: ..
  #    dockerfile: ./docker/Dockerfile
  #    args:
  #      RELEASE_VERSION: 9.0.2

 # visualizer:
 #   extends:
 #     file: ./services/visualizer.yml
 #     service: visualizer
 #   ports:
 #     - "8081:8050"  # Expose visualizer directly

  #sig-provider:
  #  extends:
  #    file: ./services/sig-provider.yml
  #    service: sig-provider
  #  ports:
  #    - "8082:8050"  # Expose sig-provider directly

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats
    ports:
      - "8080:8050"  # Expose stats service directly

  user-ops-indexer:
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer
    ports:
      - "8083:8050"  # Expose user-ops-indexer directly
